sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
env:
  global:
    - PROJECTS=$( find . -name pom.xml -print -or -path '*/target/*' -prune | sort | xargs -n 1 dirname )
cache:
  directories:
    - $HOME/.m2
install:
  # The Maven install provided by Travis is outdated, use Maven wrapper to get the latest version
  - mvn -N io.takari:maven:wrapper
  - ./mvnw -v
  # first run to download all the Maven dependencies without logging
  - MVNW=$( readlink -f ./mvnw ) ;
    for project in $PROJECTS ;
    do
        pushd "$project" ;
        $MVNW -B -q clean package -DskipTests=true || exit $? ;
        popd ;
    done
script:
  - MVNW=$( readlink -f ./mvnw ) ;
    for project in $PROJECTS ;
    do
        pushd "$project" ;
        $MVNW clean verify || exit $? ;
        popd ;
    done
